language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install libev-dev
  - sudo apt-get install libasound2-dev
  - sudo apt-get install libx264-dev
  - git clone --depth 1 git://git.videolan.org/bitstream.git
  - sudo make -C bitstream install

before_script: autoreconf -i

script: "./configure && make && make check"

notifications:
  irc:
    channels:
      - "chat.freenode.net#upipe"
    on_success: never
    on_failure: always
