language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install libev-dev
  - sudo apt-get install libasound2-dev
  - sudo apt-get install libx264-dev
  - git clone --depth 1 git://git.videolan.org/bitstream.git
  - sudo make -C bitstream install
  - curl http://ffmpeg.org/releases/ffmpeg-2.7.1.tar.bz2 | tar -xj
  - cd ffmpeg-2.7.1
  - ./configure
    --disable-all
    --disable-doc
    --disable-libxcb
    --disable-sdl
    --disable-xlib
    --disable-iconv
    --enable-avutil
    --enable-avformat
    --enable-avcodec
    --enable-swscale
    --enable-swresample
  - sudo make install

before_script: autoreconf -i

script: ./configure && make && make check

after_failure: test -r tests/test-suite.log && cat tests/test-suite.log

notifications:
  irc:
    channels:
      - "chat.freenode.net#upipe"
    on_success: never
    on_failure: always
