language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind
  - sudo apt-get install -y libev-dev

before_script: autoreconf -i

script: "./configure && make && make check"

notifications:
  irc:
    channels:
      - "chat.freenode.net#upipe"
    on_success: never
    on_failure: always
